#!/bin/sh
### BEGIN INIT INFO
# Provides: player-agent
# Required-Start: $remote_fs $syslog bluetooth pulseaudio
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: plays mp3 files in a predestined folder
# Description: Start Player-Agent at boot time.
### END INIT INFO
# /etc/init.d/player-agent
USER=root
HOME=/root
export USER HOME

. /lib/lsb/init-functions


case "$1" in
start)
start-stop-daemon -S -x /home/pi/player &
;;
stop)
start-stop-daemon -K -x /home/pi/player
;;
*)
echo "Usage: /etc/init.d/player-agent {start|stop}"
exit 1
;;
esac
exit 0
